### PR TITLE
TASK: Skip commit that don't start with "Merge pull request"

### PR DESCRIPTION
**Pull request by dfeyer**
This resolve a crash is some merge commit are reverted

### CODE REVIEW

**Comment by kdambekalns** [comment]
@kitsunet is this still needed? Did you solve that in some other way?

**Comment by kitsunet** [comment]
IMHO still needed

**Comment by kdambekalns** [comment]
Well, then feel free to merge if you agree. To me it looks sensible.

**Comment by dfeyer** [comment]
Did anything change regarding those scripts after the CI changes ?

**Comment by kitsunet** [comment]
apparently not, otherwise there would be a conflict? I merge...

**Pull request merged**
