### PR TITLE
TASK: Prefer installing of neos packages from source

### PR DESCRIPTION
**Pull request by mficzel**
Since this is the development distribution for flow composer should install all neos packages from source.

See https://getcomposer.org/doc/06-config.md#preferred-install

resolves: #71

### CODE REVIEW

**Review by kdambekalns — COMMENTED** [review]
While this is pretty specific, I usually want dev versions of Flowpack or other packages downloaded as source, too. I'd personally prefer a generic `auto` setting in the distributions…

**Comment by mficzel** [comment]
@kdambekalns we can add *:auto at any time later. I suggest to ask for now wether neos/*:source makes sense.

**Review by daniellienert — APPROVED** [review]

**Comment by albe** [comment]
What about flowpack/* as in the neos dist? Does that make sense here too?

**Review by albe — APPROVED** [review]

**Comment by mficzel** [comment]
@albe am not aware of flowpack packages that are regularly used in the flow dev dist … we can add it later if this is wrong

**Pull request merged**
